Update GSoD-interest.md for 2021
chaoss/governance pull request #247
Opened 2021-03-26 02:21 UTC by vchrombie

This commit updates the GSoD Interest page for the year 2021.

2021-03-26 02:36 UTC, GeorgLink requested changes
How about we keep or update the instructions to inform applicants what they need to do?

2021-03-26 02:36 UTC, GeorgLink commented on GSoD-interest.md
> -If you are interested in participating in Season of Docs as a technical writer, first familiarize yourself with the technical writer guide at https://goo.gl/dMVSQ8 and the technical writer responsibi
Maybe keep this?

2021-03-26 02:36 UTC, GeorgLink commented on GSoD-interest.md
> -You must complete these things by July 9, 2020 at 18:00 UTC. Make sure to also submit the [Technical Writer Application Form for 2020 Season of Docs](https://bit.ly/gsod-tw-app), provided by Google.
Maybe update the process we follow for applicants this year?

2021-04-04 19:39 UTC, vchrombie commented on GSoD-interest.md
> -If you are interested in participating in Season of Docs as a technical writer, first familiarize yourself with the technical writer guide at https://goo.gl/dMVSQ8 and the technical writer responsibi
Okay :+1:

2021-04-06 13:14 UTC, GeorgLink commented on GSoD-interest.md
> +This document serves the purpose of Statement of Interest which has to be submitted by the technical writers. Please read about it, [Creating a statement of interest | Season of Docs](https://develop
```suggestion
Adding a link to your document below serves the purpose of Statement of Interest which has to be submitted by the technical writers. Please read about it, [Creating a statement of interest | Season of Docs](https://developers.google.com/season-of-docs/docs/tech-writer-statement).
```

2021-04-06 13:15 UTC, GeorgLink requested changes
I just have one small minor edit and then this looks good

2021-04-06 13:15 UTC, merged