Add extra description for beginner contributors
chaoss/governance pull request #251
Opened 2021-03-31 00:27 UTC by seun-beta

Added extra description for beginner contributors. Also fixed some typos. I was thinking of making the tone of the docs more friendly.

2021-04-02 12:22 UTC, GeorgLink requested changes
Thanks @seun-beta. This is great. I have a few change requests.

2021-04-02 12:22 UTC, GeorgLink commented on CONTRIBUTING.md
> +- [CHAOSS on Community Bridge](https://tinyurl.com/y6bao886)
```suggestion
- [CHAOSS on LFX Crowdfunding](https://crowdfunding.lfx.linuxfoundation.org/projects/a4a43b66-f707-47b4-97cc-484285c274a8)
- [CHAOSS on Open Collective](https://opencollective.com/chaoss) 
```

2021-04-02 12:22 UTC, GeorgLink commented on CONTRIBUTING.md
> +- [x] Please describe your pull request.
```suggestion
- [ ] Check if your code addition will pass both code linting checks and unit test.  
- [ ] Check if your documentation commits are free from typos.
- [ ] Check the commits and commits messages and ensure they are free from typos.
- [ ] Please describe your pull request.  
```

2021-04-06 07:56 UTC, seun-beta commented
Hello @GeorgLink I have committed the suggested changes. Apologies for the late response, I was on Easter break.

2021-04-06 12:04 UTC, GeorgLink approved these changes
Thanks @seun-beta 

I hope you had a great Easter break

2021-04-06 12:04 UTC, merged